apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: test-and-report-action
description: "Run automated e2e tests and publish the results"

inputs:
  environment:
    description: "Deployment environment for testing"
    required: true

  test_tag:
    description: "Tag for filtering tests"
    required: true
  
  username:
    description: "Enter the username specific to features"
    required: true


runs:
  using: composite
  steps:

      - name: call cdro
        if: ${{ inputs.username == 'cdro' }}
        uses: ./.cloudbees/pods/cd-ro
        with:
            environment: ${{ inputs.test_tag }}
            test_tag: ${{ inputs.environment }}
            username: ${{ inputs.username }}

      - name: Print details
        if: ${{ inputs.username == 'fm' }}
        uses: ./.cloudbees/pods/fm
        with:
            environment: ${{ inputs.test_tag }}
            test_tag: ${{ inputs.environment }}
            username: ${{ inputs.username }}
